# -*- coding: utf-8 -*-
"""data_Report

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LcelK5BIoYEjj5SISEcjJxyjt4Er3ppT
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler, RobustScaler, MinMaxScaler, KBinsDiscretizer, PolynomialFeatures
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import VarianceThreshold, SelectKBest, mutual_info_classif
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, roc_auc_score, confusion_matrix, RocCurveDisplay
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import RandomizedSearchCV

data = pd.read_csv('aug_train.csv')
# ==========================
# 1️⃣ last_new_job
# ==========================
data['last_new_job'] = data['last_new_job'].replace({
    'never': '0',
    '>4': '5'
})
data['last_new_job'] = pd.to_numeric(data['last_new_job'], errors='coerce')

# ==========================
# 2️⃣ experience
# ==========================
data['experience'] = data['experience'].replace({
    '>20': '21',
    '<1': '0',
    'other': np.nan
})
data['experience'] = pd.to_numeric(data['experience'], errors='coerce')

# ==========================
# 3️⃣ company_size — version corrigée
# ==========================
def parse_company_size(value):
    if pd.isna(value):
        return np.nan
    value = str(value).strip()

    # ✅ suppression des mots parasites comme "oct", "to", etc.
    value = value.replace("oct", "").replace("to", "").replace("–", "-").replace("—", "-")

    # Cas 1 : commence par <
    if value.startswith('<'):
        try:
            return int(value[1:])
        except:
            return np.nan

    # Cas 2 : contient un intervalle 10-49
    elif '-' in value:
        try:
            low, high = value.split('-')
            low = ''.join(filter(str.isdigit, low))
            high = ''.join(filter(str.isdigit, high))
            return (int(low) + int(high)) / 2
        except:
            return np.nan

    # Cas 3 : commence par >
    elif value.startswith('>'):
        try:
            return int(value[1:])
        except:
            return np.nan

    # Cas 4 : nombre seul
    else:
        try:
            return int(''.join(filter(str.isdigit, value)))
        except:
            return np.nan

data['company_size'] = data['company_size'].apply(parse_company_size)

# ==========================
# Vérification du résultat
# ==========================
data.describe()

print(data.info())

missing_df = data.isnull().astype(int)
missing_counts = missing_df.sum()

missing_percent = (data.isnull().sum() / len(data)) * 100
missing_info = pd.DataFrame({
    "Valeurs manquantes": data.isnull().sum(),
    "% du total": missing_percent
})
print(missing_info)

plt.figure(figsize=(8,5))
sns.barplot(
    x=missing_counts.index,
    y=missing_counts.values,
    hue=missing_counts.index,
    palette="viridis",
    legend=False
)
plt.ylabel("Nombre de valeurs manquantes")
plt.xlabel("Colonnes")
plt.title("Valeurs manquantes par colonne")
plt.xticks(rotation=45)
plt.show()

# ===============================
# 2️⃣ Suppression des lignes avec valeurs manquantes
#     dans certaines colonnes critiques
# ===============================
cols_drop_na = ['gender','experience','last_new_job','company_type','company_size', 'enrolled_university', 'education_level', 'major_discipline']

# Suppression des lignes contenant des NaN dans ces colonnes
data = data.dropna(subset=cols_drop_na)
print("Shape après suppression des lignes avec NaN :", data.shape)

# ===============================
# 3️⃣ Imputation du company_size
#     → par la moyenne (mean) après conversion en numérique
# ===============================

def parse_company_size(value):
    """Convertit les valeurs textuelles de company_size en valeur numérique moyenne d'intervalle."""
    if pd.isna(value):
        return np.nan
    value = str(value).strip()
    value = value.replace("oct", "").replace("to", "").replace("–", "-").replace("—", "-")

    if value.startswith('<'):
        try:
            return int(value[1:])
        except:
            return np.nan
    elif '-' in value:
        try:
            low, high = value.split('-')
            low = ''.join(filter(str.isdigit, low))
            high = ''.join(filter(str.isdigit, high))
            return (int(low) + int(high)) / 2
        except:
            return np.nan
    elif value.startswith('>'):
        try:
            return int(value[1:])
        except:
            return np.nan
    else:
        try:
            return int(''.join(filter(str.isdigit, value)))
        except:
            return np.nan

# ===============================
# 5️⃣ Vérification du nettoyage
# ===============================
print("\nValeurs manquantes restantes :")
print(data.isna().sum().sort_values(ascending=False).head(10))

numeric_cols = data.select_dtypes(include=['int64', 'float64']).columns.tolist()
print("Colonnes numériques analysées :", numeric_cols)

# ===============================
# 2️⃣ Création des boxplots côte à côte
# ===============================
plt.figure(figsize=(18, 6))  # Taille globale
plt.suptitle("Boxplots Avant nettoyage complet des valeurs aberrantes", fontsize=14, fontweight='bold')

# Boucle sur les variables
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(1, len(numeric_cols), i)
    sns.boxplot(y=data[col], color='lightblue')
    plt.title(col, fontsize=9)
    plt.xlabel("")
    plt.ylabel("")

plt.tight_layout(rect=[0, 0, 1, 0.95])  # Ajuste les marges
plt.show()

# ==========================================
# 🧹 Nettoyage complet des valeurs aberrantes (Z-score)
# ==========================================

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

# ==========================================
# 1️⃣ Définir la fonction de nettoyage
# ==========================================
def remove_outliers_zscore(df, cols, threshold):
    """
    Supprime les valeurs aberrantes selon la méthode du Z-score.

    Paramètres :
    - df : DataFrame d'origine
    - cols : liste des colonnes à nettoyer
    - threshold : seuil (en écart-types) au-delà duquel une valeur est considérée aberrante
    """
    df_clean = df.copy()

    for col in cols:
        if col in df_clean.columns:
            # Calcul du Z-score absolu (en conservant l’index)
            z_scores = np.abs(stats.zscore(df_clean[col].dropna()))
            z_scores = pd.Series(z_scores, index=df_clean[col].dropna().index)

            # Comptage avant suppression
            before = df_clean.shape[0]

            # Suppression des valeurs aberrantes
            df_clean = df_clean[(z_scores < threshold) | (df_clean[col].isna())]

            # Comptage après suppression
            after = df_clean.shape[0]

            print(f"→ {col} : {before - after} valeurs aberrantes supprimées (Z-score > {threshold})")

    return df_clean


# ==========================================
# 2️⃣ Colonnes à traiter
# ==========================================
cols_zscore = {
    'city_development_index': 0.64,
    'company_size': 0.5,
    'training_hours': 1.45
}

# ==========================================
# 3️⃣ Application du nettoyage progressif
# ==========================================
data_clean = data.copy()

for col, threshold in cols_zscore.items():
    data_clean = remove_outliers_zscore(data_clean, [col], threshold)

print("\nShape avant nettoyage :", data.shape)
print("Shape après nettoyage :", data_clean.shape)


# ==========================================
# 4️⃣ Visualisation globale : boxplots avant/après
# ==========================================
numeric_cols = [
    'enrollee_id', 'city_development_index', 'experience',
    'company_size', 'last_new_job', 'training_hours', 'target'
]

# 2️⃣ Création des boxplots côte à côte
# ===============================
plt.figure(figsize=(18, 6))  # Taille globale
plt.suptitle("Boxplots Avant nettoyage complet des valeurs aberrantes", fontsize=14, fontweight='bold')

# Boucle sur les variables
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(1, len(numeric_cols), i)
    sns.boxplot(y=data[col], color='lightblue')
    plt.title(col, fontsize=9)
    plt.xlabel("")
    plt.ylabel("")

plt.tight_layout(rect=[0, 0, 1, 0.95])  # Ajuste les marges
plt.show()

# --- Après nettoyage ---
plt.figure(figsize=(18, 5))
for i, col in enumerate(numeric_cols, start=1):
    plt.subplot(1, len(numeric_cols), i)
    sns.boxplot(y=data_clean[col], color='lightgreen')
    plt.title(col)
plt.suptitle("Boxplots Après nettoyage complet des valeurs aberrantes", fontsize=14)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

from sklearn.preprocessing import OneHotEncoder

# Sélection des colonnes catégorielles
cat_cols = data_clean.select_dtypes(include=['object']).columns.tolist()

# Encodage OneHot
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoded = pd.DataFrame(encoder.fit_transform(data_clean[cat_cols]), columns=encoder.get_feature_names_out(cat_cols))

# Fusion avec les colonnes numériques
data_encoded = pd.concat([data_clean.drop(columns=cat_cols), encoded], axis=1)
print("✅ Données après encodage :", data_encoded.shape)

num_cols = data_clean.select_dtypes(include=[np.number]).columns.tolist()

corr = data_clean[num_cols].corr()
plt.figure(figsize=(12,10))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="RdBu_r", center=0)
plt.title("Matrice de corrélation (Pearson) — features numériques")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import chi2_contingency

# ============================================================
# 📊 Heatmap de l'association entre toutes les variables qualitatives
# ============================================================

# 1️⃣ Sélection des colonnes qualitatives
cat_cols = data_clean.select_dtypes(include=['object', 'category']).columns.tolist()
print("Variables qualitatives détectées :", cat_cols)

# ------------------------------------------------------------
# 2️⃣ Fonction de calcul de Cramér’s V
# ------------------------------------------------------------
def cramers_v(x, y):
    """Calcule le coefficient de Cramér’s V entre deux variables qualitatives."""
    confusion_matrix = pd.crosstab(x, y)
    chi2 = chi2_contingency(confusion_matrix, correction=False)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt((chi2 / n) / (min(k - 1, r - 1)))

# ------------------------------------------------------------
# 3️⃣ Calcul de la matrice des associations
# ------------------------------------------------------------
cramers_results = pd.DataFrame(index=cat_cols, columns=cat_cols, dtype=float)

for col1 in cat_cols:
    for col2 in cat_cols:
        if col1 == col2:
            cramers_results.loc[col1, col2] = 1.0
        else:
            cramers_results.loc[col1, col2] = cramers_v(data_clean[col1], data_clean[col2])

# ------------------------------------------------------------
# 4️⃣ Visualisation sous forme de heatmap
# ------------------------------------------------------------
plt.figure(figsize=(10,8))
sns.heatmap(cramers_results.astype(float), annot=True, cmap="YlGnBu", vmin=0, vmax=1, fmt=".2f")
plt.title("🔥 Heatmap des associations entre variables qualitatives (Cramér’s V)", fontsize=14, fontweight='bold')
plt.xlabel("Variables qualitatives")
plt.ylabel("Variables qualitatives")
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import RobustScaler
from sklearn.decomposition import PCA
import plotly.express as px
import plotly.graph_objects as go

# ============================================================
# 🧠 PCA robuste + visualisations interactives
# ============================================================

# 1️⃣ Sélection des colonnes numériques pertinentes
num_cols = ['city_development_index', 'experience', 'company_size', 'last_new_job', 'training_hours']
print("Colonnes utilisées pour le PCA :", num_cols)

X = data[num_cols]
y = data['target'] if 'target' in data_clean.columns else None

# ------------------------------------------------------------
# 2️⃣ Mise à l’échelle robuste
# ------------------------------------------------------------
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)
print("\n✅ Données standardisées avec RobustScaler (robuste aux valeurs extrêmes)")

# ------------------------------------------------------------
# 3️⃣ Application du PCA
# ------------------------------------------------------------
pca = PCA(n_components=len(num_cols))
X_pca = pca.fit_transform(X_scaled)

# ------------------------------------------------------------
# 4️⃣ Tableau des composantes principales (eig)
# ------------------------------------------------------------
eig = pd.DataFrame({
    "Dimension": [f"Dim{x + 1}" for x in range(len(pca.explained_variance_))],
    "Variance expliquée": pca.explained_variance_,
    "% variance expliquée": np.round(pca.explained_variance_ratio_ * 100, 2),
    "% cum. var. expliquée": np.round(np.cumsum(pca.explained_variance_ratio_) * 100, 2)
})
print("\n🧾 Tableau des composantes principales :")
print(eig)

# ------------------------------------------------------------
# 5️⃣ Scree Plot interactif
# ------------------------------------------------------------
fig = go.Figure()
fig.add_trace(go.Bar(
    x=eig["Dimension"],
    y=eig["% variance expliquée"],
    name="Variance expliquée (%)",
    marker_color='skyblue'
))
fig.add_trace(go.Scatter(
    x=eig["Dimension"],
    y=eig["% cum. var. expliquée"],
    name="Variance cumulée (%)",
    mode='lines+markers',
    line=dict(color='red', width=2)
))
fig.update_layout(
    title="📈 Variance expliquée et cumulée (PCA)",
    xaxis_title="Composantes principales",
    yaxis_title="Pourcentage de variance (%)",
    template="plotly_white"
)
fig.show()

def plot_correlation_circle(pca, features, pc1=0, pc2=1):
    """Trace le cercle de corrélation (relation entre variables et axes principaux)."""
    plt.figure(figsize=(10, 7))
    plt.axhline(0, color='gray', linestyle='--', lw=0.8)
    plt.axvline(0, color='gray', linestyle='--', lw=0.8)

    # Cercle de corrélation
    circle = plt.Circle((0, 0), 1, color='blue', fill=False, linestyle='--')
    plt.gca().add_artist(circle)

    # 🔹 Flèches plus grandes
    for i, (x, y) in enumerate(zip(pca.components_[pc1, :], pca.components_[pc2, :])):
        plt.arrow(0, 0, x, y,
                  color='red',
                  alpha=0.7,
                  width=0.01,        # ➜ plus épais
                  head_width=0.05,   # ➜ pointe plus grande
                  length_includes_head=True)
        plt.text(x * 1.15, y * 1.15, features[i], fontsize=11, fontweight='bold')

    plt.xlabel(f"PC{pc1+1} ({pca.explained_variance_ratio_[pc1]*100:.2f}%)")
    plt.ylabel(f"PC{pc2+1} ({pca.explained_variance_ratio_[pc2]*100:.2f}%)")
    plt.title(f"🎯 Cercle de corrélation (PC{pc1+1} vs PC{pc2+1})")
    plt.xlim(-1.1, 1.1)
    plt.ylim(-1.1, 1.1)
    plt.grid(alpha=0.3)
    plt.show()

# Exemple d’appel
plot_correlation_circle(pca, X.columns)

# ============================================================
# 🔍 Importance des variables d'après le PCA (loadings)
# ============================================================
loadings = pd.DataFrame(
    pca.components_.T,
    columns=[f"PC{i+1}" for i in range(pca.n_components_)],
    index=num_cols
)

# Calcul de l’importance totale de chaque variable (somme des poids absolus)
loadings["importance_totale"] = loadings.abs().sum(axis=1)

# Tri des variables par importance
loadings_sorted = loadings.sort_values("importance_totale", ascending=False)
print("\nImportance totale des variables selon le PCA :")
print(loadings_sorted)

# ============================================================
# ✂️ Sélection automatique des variables les plus utiles
# ============================================================
# Exemple : garder les variables ayant une importance > 0.5
threshold = 0.5
selected_features = loadings_sorted[loadings_sorted["importance_totale"] > threshold].index

print("\n✅ Variables conservées après analyse PCA :", list(selected_features))

# Créer un dataset réduit
data_pca_reduced = data_clean[selected_features]
print("Shape du nouveau dataset :", data_pca_reduced.shape)

plt.figure(figsize=(7,4))
sns.barplot(x=loadings_sorted.index, y=loadings_sorted["importance_totale"], palette="viridis")
plt.title("Importance totale des variables selon le PCA")
plt.ylabel("Importance totale (somme des poids absolus)")
plt.xticks(rotation=30)
plt.show()

data_clean.info()

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
import xgboost as xgb
import warnings
warnings.filterwarnings("ignore")

X = data_clean.drop(columns=["target"])
y = data_clean["target"]

cat_cols = X.select_dtypes(include="object").columns
num_cols = X.select_dtypes(exclude="object").columns

preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
    ("num", StandardScaler(), num_cols)
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

X_train_pp = preprocessor.fit_transform(X_train)
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_pp, y_train)

# ===========================================================
# 2️⃣ Random Forest – Hyperparamètres
# ===========================================================
param_grid_rf = {
    "n_estimators": [20, 40, 60],
    "max_depth": [2, 4, 6],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "class_weight": ["balanced"]
}

rf_search = RandomizedSearchCV(
    RandomForestClassifier(random_state=42),
    param_distributions=param_grid_rf,
    n_iter=10,
    scoring="f1",
    cv=3,
    n_jobs=-1,
    random_state=42
)
rf_search.fit(X_train_pp, y_train)
print("\nBest RF Params:", rf_search.best_params_)

rf_best = Pipeline([
    ("prep", preprocessor),
    ("rf", RandomForestClassifier(**rf_search.best_params_, random_state=42))
])
rf_best.fit(X_train, y_train)
y_pred_rf = rf_best.predict(X_test)
y_prob_rf = rf_best.predict_proba(X_test)[:, 1]

# ===========================================================
# 3️⃣ XGBoost – Hyperparamètres
# ===========================================================
xgb_clf = xgb.XGBClassifier(objective='binary:logistic', eval_metric='logloss', random_state=42)
param_grid_xgb = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [3, 5, 7],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0]
}

xgb_search = RandomizedSearchCV(
    xgb_clf, param_grid_xgb,
    n_iter=20, cv=3, scoring="f1",
    n_jobs=-1, random_state=42
)
X_train_pp2 = preprocessor.transform(X_train)
xgb_search.fit(X_train_pp2, y_train)
print("\nBest XGBoost Params:", xgb_search.best_params_)

xgb_best = Pipeline([
    ("prep", preprocessor),
    ("xgb", xgb.XGBClassifier(**xgb_search.best_params_, eval_metric="logloss", random_state=42))
])
xgb_best.fit(X_train, y_train)
y_pred_xgb = xgb_best.predict(X_test)
y_prob_xgb = xgb_best.predict_proba(X_test)[:, 1]

compare_df = pd.DataFrame({
    "Modèle": ["Random Forest", "XGBoost"],
    "Accuracy": [accuracy_score(y_test, y_pred_rf), accuracy_score(y_test, y_pred_xgb)],
    "F1-score": [f1_score(y_test, y_pred_rf), f1_score(y_test, y_pred_xgb)],
    "ROC-AUC": [roc_auc_score(y_test, y_prob_rf), roc_auc_score(y_test, y_prob_xgb)]
})
print("\n📊 COMPARAISON DES MODÈLES")
print(compare_df)

def generate_enterprise_recommendation(prob, threshold=0.5):
    if prob >= 0.8:
        return "Risque élevé : former le personnel et suivre immédiatement."
    elif prob >= threshold:
        return "Risque modéré : surveiller et envisager formation ciblée."
    else:
        return "Risque faible : maintenir les bonnes pratiques."

# Random Forest
results_rf = X_test.copy()
results_rf["Prédiction"] = y_pred_rf
results_rf["Probabilité_Positive"] = y_prob_rf
results_rf["Recommandation"] = [generate_enterprise_recommendation(p) for p in y_prob_rf]

# XGBoost
results_xgb = X_test.copy()
results_xgb["Prédiction"] = y_pred_xgb
results_xgb["Probabilité_Positive"] = y_prob_xgb
results_xgb["Recommandation"] = [generate_enterprise_recommendation(p) for p in y_prob_xgb]

print("\nExemple risque élevé (prob >= 0.8)")
print(final_results[final_results["Probabilité_Positive"] >= 0.8][["Prédiction", "Probabilité_Positive", "Recommandation"]].head(5))

print("\nExemple risque modéré (0.5 <= prob < 0.8)")
print(final_results[(final_results["Probabilité_Positive"] >= 0.5) & (final_results["Probabilité_Positive"] < 0.8)][["Prédiction", "Probabilité_Positive", "Recommandation"]].head(5))

print("\nExemple risque faible (prob < 0.5)")
print(final_results[final_results["Probabilité_Positive"] < 0.5][["Prédiction", "Probabilité_Positive", "Recommandation"]].head(5))

import matplotlib.pyplot as plt
import seaborn as sns

# ===========================================================
# 8️⃣ Visualisation des performances
# ===========================================================
# 1️⃣ Comparaison Accuracy, F1-score, ROC-AUC
plt.figure(figsize=(10,5))
metrics_plot = compare_df.melt(id_vars="Modèle", var_name="Métrique", value_name="Score")
sns.barplot(data=metrics_plot, x="Métrique", y="Score", hue="Modèle")
plt.title("Comparaison des métriques des modèles")
plt.ylim(0,1)
plt.show()

# 2️⃣ Distribution des probabilités prédites
plt.figure(figsize=(10,5))
sns.histplot(y_prob_rf, bins=20, kde=True, color="skyblue", label="Random Forest", alpha=0.6)
sns.histplot(y_prob_xgb, bins=20, kde=True, color="salmon", label="XGBoost", alpha=0.6)
plt.axvline(0.5, color='black', linestyle='--', label='Seuil 0.5')
plt.xlabel("Probabilité prédite de risque")
plt.ylabel("Nombre d'observations")
plt.title("Distribution des probabilités positives par modèle")
plt.legend()
plt.show()

# 3️⃣ Visualisation des recommandations
plt.figure(figsize=(8,4))
recommend_counts = final_results['Recommandation'].value_counts()
sns.barplot(x=recommend_counts.index, y=recommend_counts.values, palette="Set2")
plt.ylabel("Nombre de cas")
plt.title("Répartition des recommandations finales")
plt.xticks(rotation=30)
plt.show()

# 4️⃣ Heatmap de confusion (optionnel pour Random Forest)
from sklearn.metrics import confusion_matrix
import numpy as np

cm = confusion_matrix(y_test, y_pred_rf)
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=[0,1], yticklabels=[0,1])
plt.xlabel("Prédit")
plt.ylabel("Réel")
plt.title("Matrice de confusion – Random Forest")
plt.show()